# Generated by Django 3.1 on 2020-08-14 12:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20200814_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='post_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
