# Generated by Django 3.1 on 2020-08-19 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_article_snippet'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='artPix',
            field=models.ImageField(blank=True, default='img.jpeg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='article',
            name='snippet',
            field=models.CharField(max_length=255),
        ),
    ]
