# Generated by Django 3.1 on 2020-08-20 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_auto_20200820_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='artPix',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
