# Generated by Django 3.1 on 2020-08-21 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0018_auto_20200821_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='artPix',
            field=models.ImageField(blank=True, default='djan.jpg', null=True, upload_to='images'),
        ),
    ]
